#!/data/data/com.termux/files/usr/bin/sh

export SSH_AUTH_SOCK=$HOME/.ssh-agent-socket
SELECT=`termux-dialog radio -t "Toggle screen sleep" -v On,Off | jq -r .index`
if [ "$SELECT" = "0" ]; then
    ssh charlie@192.0.2.3 DISPLAY=:0.0 xset dpms force on
elif [ "$SELECT" = "1" ]; then
    ssh charlie@192.0.2.3 DISPLAY=:0.0 xset dpms force off
fi
